<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Ordens_Estado;

class EstilosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $estilos = [
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Fondo",
                "variable"=>"body_bg",
                "elemento"=>".style_fondo_bg",
                "propiedad"=>"background-color",
                "valor"=>"#FFFFFF",
                "posicion"=>1,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Fondo Header",
                "variable"=>"bg",
                "elemento"=>".style-header-bg",
                "propiedad"=>"background-color",
                "valor"=>"rgb(0, 0, 0)",
                "posicion"=>2,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Color Icono Menú Móvil",
                "variable"=>"",
                "elemento"=>".mobile-menu-icon",
                "propiedad"=>"color",
                "valor"=>"#ffffff",
                "posicion"=>3,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Menu principal",
                "variable"=>"",
                "elemento"=>".style-nav",
                "propiedad"=>"background-color",
                "valor"=>"#000000",
                "posicion"=>4,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"textos de Menu principal (links)",
                "variable"=>"",
                "elemento"=>".as-menu-links-style",
                "propiedad"=>"color",
                "valor"=>"#080808",
                "posicion"=>5,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Menu principal Desplegable",
                "variable"=>"",
                "elemento"=>".style-nav-dropdown",
                "propiedad"=>"background-color",
                "valor"=>"#141414",
                "posicion"=>6,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Menu principal Desplegable (links)",
                "variable"=>"",
                "elemento"=>".style-nav-dropdown",
                "propiedad"=>"color",
                "valor"=>"#ffffff",
                "posicion"=>7,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Menu principal Desplegable (hover)",
                "variable"=>"",
                "elemento"=>".style-nav-dropdown:hover",
                "propiedad"=>"background-color",
                "valor"=>"rgb(243, 103, 27)",
                "posicion"=>8,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Menu principal Desplegable Móvil",
                "variable"=>"",
                "elemento"=>".style-nav-mobile",
                "propiedad"=>"background-color",
                "valor"=>"#141414",
                "posicion"=>9,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Menu principal Desplegable Móvil (links)",
                "variable"=>"",
                "elemento"=>".style-nav-mobile .links-mobile",
                "propiedad"=>"color",
                "valor"=>"#fff",
                "posicion"=>10,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Ícono Buscar (Menú Principal)",
                "variable"=>"",
                "elemento"=>".btn-search-mobile i",
                "propiedad"=>"color",
                "valor"=>"#212529",
                "posicion"=>11,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Ícono Carrito (Menú Principal)",
                "variable"=>"",
                "elemento"=>".btn-cart i",
                "propiedad"=>"color",
                "valor"=>"#ffffff",
                "posicion"=>12,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Ícono Carrito Contador(textos)",
                "variable"=>"",
                "elemento"=>".btn-cart .counter",
                "propiedad"=>"color",
                "valor"=>"#ffffff",
                "posicion"=>13,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Ícono Carrito Contador (fondo)",
                "variable"=>"",
                "elemento"=>".style-nav .carrito .counter",
                "propiedad"=>"background-color",
                "valor"=>"rgb(243, 103, 27)",
                "posicion"=>14,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Botón comprar (texto)",
                "variable"=>"",
                "elemento"=>".style-btn-comprar",
                "propiedad"=>"color",
                "valor"=>"#ffffff",
                "posicion"=>15,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Botón comprar (fondo)",
                "variable"=>"",
                "elemento"=>".style-btn-comprar",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63, 63, 189)",
                "posicion"=>16,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Botón Ver Todo Front (fondo)",
                "variable"=>"",
                "elemento"=>".btn-ver-todo",
                "propiedad"=>"background-color",
                "valor"=>"#000000",
                "posicion"=>17,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Botón Ver Todo Front (texto)",
                "variable"=>"",
                "elemento"=>".btn-ver-todo",
                "propiedad"=>"color",
                "valor"=>"#ffffff",
                "posicion"=>18,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Flecha Carrousel Izquierda",
                "variable"=>"",
                "elemento"=>".owl-prev",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63, 63, 189)",
                "posicion"=>19,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Flecha Carrousel Izquierda (icono)",
                "variable"=>"",
                "elemento"=>".btn-carrousel-prev",
                "propiedad"=>"color",
                "valor"=>"rgb(255, 255, 255)",
                "posicion"=>20,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Flecha Carrousel Derecha",
                "variable"=>"",
                "elemento"=>".owl-next",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63, 63, 189)",
                "posicion"=>21,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Flecha Carrousel Derecha (icono)",
                "variable"=>"",
                "elemento"=>".btn-carrousel-next",
                "propiedad"=>"color",
                "valor"=>"rgb(255, 255, 255)",
                "posicion"=>22,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Footer",
                "variable"=>"",
                "elemento"=>".as-footer-style",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63, 63, 189)",
                "posicion"=>23,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Footer (Copyright)",
                "variable"=>"",
                "elemento"=>".as-copyright-style",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63, 63, 189)",
                "posicion"=>24,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Footer principal (texto)",
                "variable"=>"",
                "elemento"=>".style-footer",
                "propiedad"=>"color",
                "valor"=>"rgb(255, 255, 255)",
                "posicion"=>25,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Footer secundario (texto)",
                "variable"=>"",
                "elemento"=>".style-footer-bottom",
                "propiedad"=>"color",
                "valor"=>"rgb(255, 255, 255)",
                "posicion"=>26,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Menu Footer",
                "variable"=>"",
                "elemento"=>".style-menu-footer",
                "propiedad"=>"color",
                "valor"=>"rgb(226, 226, 236)",
                "posicion"=>28,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Efecto banner",
                "variable"=>"",
                "elemento"=>".banner-brand a",
                "propiedad"=>"background-color",
                "valor"=>"linear-gradient(45deg, rgb(196,255,0) , rgb(0,171,111) )",
                "posicion"=>29,
                "oculto"=>1,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Menú categoría",
                "variable"=>"",
                "elemento"=>".style-category-nav",
                "propiedad"=>"background-color",
                "valor"=>"#000000",
                "posicion"=>30,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Menú categoría (activa)",
                "variable"=>"",
                "elemento"=>".style-category-nav-active",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63, 63, 189)",
                "posicion"=>31,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Submenú categoría",
                "variable"=>"",
                "elemento"=>"level2style",
                "propiedad"=>"color",
                "valor"=>"#000000",
                "posicion"=>32,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Menú categoría links",
                "variable"=>"",
                "elemento"=>".style-category-nav a",
                "propiedad"=>"color",
                "valor"=>"#ffffff",
                "posicion"=>33,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Menú categoría links (activa)",
                "variable"=>"",
                "elemento"=>".style-category-nav-active a",
                "propiedad"=>"color",
                "valor"=>"#ffffff",
                "posicion"=>34,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Submenú categoría (activa)",
                "variable"=>"",
                "elemento"=>".level2-active",
                "propiedad"=>"color",
                "valor"=>"rgb(63, 63, 189)",
                "posicion"=>35,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Redes sociales (icono)",
                "variable"=>"",
                "elemento"=>".as-footer_social .btn-social",
                "propiedad"=>"color",
                "valor"=>"rgb(63, 63, 189)",
                "posicion"=>36,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Redes sociales (fondo)",
                "variable"=>"",
                "elemento"=>".as-footer_social .btn-social",
                "propiedad"=>"background",
                "valor"=>"#fff",
                "posicion"=>37,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Redes sociales (texto al pasar mouse)",
                "variable"=>"",
                "elemento"=>".as-footer_social .btn-social:hover",
                "propiedad"=>"color",
                "valor"=>"#ffffff",
                "posicion"=>38,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Redes sociales (fondo al pasar mouse)",
                "variable"=>"",
                "elemento"=>".as-footer_social .btn-social:hover",
                "propiedad"=>"background-color",
                "valor"=>"rgb(1, 1, 86)",
                "posicion"=>39,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Botón pagar carrito (texto)",
                "variable"=>"",
                "elemento"=>".btn-pay-style",
                "propiedad"=>"color",
                "valor"=>"rgb(255, 255, 255)",
                "posicion"=>40,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Botón pagar carrito (fondo)",
                "variable"=>"",
                "elemento"=>".btn-pay-style",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63, 63, 189)",
                "posicion"=>41,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Botón seguir comprando (texto)",
                "variable"=>"",
                "elemento"=>".btn-shopping-style",
                "propiedad"=>"color",
                "valor"=>"rgb(255, 255, 255)",
                "posicion"=>42,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Botón seguir comprando (fondo)",
                "variable"=>"",
                "elemento"=>".btn-shopping-style",
                "propiedad"=>"background-color",
                "valor"=>"rgb(43, 43, 43)",
                "posicion"=>43,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Botón comprar (agotado)",
                "variable"=>"",
                "elemento"=>".style-btn-agotado",
                "propiedad"=>"color",
                "valor"=>"rgb(255, 255, 255)",
                "posicion"=>44,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Botón comprar (agotado)",
                "variable"=>"",
                "elemento"=>".style-btn-agotado",
                "propiedad"=>"background-color",
                "valor"=>"#8B0000",
                "posicion"=>45,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Botón Detalles (texto)",
                "variable"=>"",
                "elemento"=>".style-btn-detalles",
                "propiedad"=>"color",
                "valor"=>"rgb(255, 255, 255)",
                "posicion"=>46,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Botón Detalles (fondo)",
                "variable"=>"",
                "elemento"=>".style-btn-detalles",
                "propiedad"=>"background-color",
                "valor"=>"#dfdede",
                "posicion"=>47,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Fondo Header Top",
                "variable"=>"bg",
                "elemento"=>".style-header-top-bg",
                "propiedad"=>"background-color",
                "valor"=>"rgb(0, 0, 0)",
                "posicion"=>2,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Botón Menú (fondo)",
                "variable"=>"bg",
                "elemento"=>".style-btn-menu",
                "propiedad"=>"background-color",
                "valor"=>"rgb(0, 0, 0)",
                "posicion"=>3,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Botón Menú (al pasar el ratón)",
                "variable"=>"bg",
                "elemento"=>".style-btn-menu:hover",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63, 63, 189)",
                "posicion"=>3,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Ícono Carrito (fondo)",
                "variable"=>"bg",
                "elemento"=>".btn-cart",
                "propiedad"=>"background-color",
                "valor"=>"#000000",
                "posicion"=>14,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Ícono Carrito (al pasar el ratón)",
                "variable"=>"bg",
                "elemento"=>".btn-cart:hover",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63, 63, 189)",
                "posicion"=>14,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"textos de Menu principal (links al pasar el ratón)",
                "variable"=>"",
                "elemento"=>".as-menu-links-style:hover span",
                "propiedad"=>"color",
                "valor"=>"#ffffff",
                "posicion"=>5,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Links Menú Principal (al pasar el ratón)",
                "variable"=>"bg",
                "elemento"=>".as-menu-links-style:hover ",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63, 63, 189)",
                "posicion"=>5,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Textos del Sub Menú (links)",
                "variable"=>"",
                "elemento"=>".as-menu-links-lvl2-style span",
                "propiedad"=>"color",
                "valor"=>"#000",
                "posicion"=>6,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Textos del Sub Menú (links al pasar el ratón)",
                "variable"=>"",
                "elemento"=>".as-menu-links-lvl2-style:hover span ",
                "propiedad"=>"color",
                "valor"=>"rgb(63, 63, 189)",
                "posicion"=>6,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Botón Cerrar Modal Carrito (fondo)",
                "variable"=>"bg",
                "elemento"=>".btn-close-cart ",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63, 63, 189)",
                "posicion"=>7,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Botón Cerrar Modal Carrito (texto)",
                "variable"=>"",
                "elemento"=>".btn-close-cart",
                "propiedad"=>"color",
                "valor"=>"#ffffff",
                "posicion"=>8,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Redes Sociales Top header (fondo)",
                "variable"=>"bg",
                "elemento"=>".style-social-links",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63,63,189)",
                "posicion"=>2,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Redes Sociales Top header (icono)",
                "variable"=>"",
                "elemento"=>".style-social-links",
                "propiedad"=>"color",
                "valor"=>"white",
                "posicion"=>2,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Redes Sociales Top Header (fondo al pasar el ratón)",
                "variable"=>"bg",
                "elemento"=>".style-social-links:hover",
                "propiedad"=>"background-color",
                "valor"=>"rgb(1,1,86)",
                "posicion"=>2,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Redes Sociales Top Header (iconos al pasar el ratón)",
                "variable"=>"",
                "elemento"=>".style-social-links:hover",
                "propiedad"=>"color",
                "valor"=>"#fff",
                "posicion"=>2,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Flecha Subir Arriba (fondo)",
                "variable"=>"bg",
                "elemento"=>".ir-arriba-style",
                "propiedad"=>"background-color",
                "valor"=>"rgb(1,1,86)",
                "posicion"=>6,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Fecha Subir Arriba (Color Icono)",
                "variable"=>"",
                "elemento"=>".ir-arriba-style",
                "propiedad"=>"color",
                "valor"=>"#fff",
                "posicion"=>7,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Botón Suscripción (fondo)",
                "variable"=>"bg",
                "elemento"=>".btn-sus-style",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63,63,189)",
                "posicion"=>8,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Botón Suscripción (texto)",
                "variable"=>"",
                "elemento"=>".btn-sus-style",
                "propiedad"=>"color",
                "valor"=>"#fff",
                "posicion"=>9,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Botón Suscripción (fondo al pasar el ratón)",
                "variable"=>"bg",
                "elemento"=>".btn-sus-style:hover",
                "propiedad"=>"background-color",
                "valor"=>"rgb(1,1,86)",
                "posicion"=>10,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Botón Suscripción (texto al pasar el ratón) ",
                "variable"=>"",
                "elemento"=>".btn-sus-style:hover",
                "propiedad"=>"color",
                "valor"=>"#fff",
                "posicion"=>11,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Titulo Página Categorías, Etiqueta, productos",
                "variable"=>"",
                "elemento"=>".as-page-title-style",
                "propiedad"=>"color",
                "valor"=>"rgb(63,63,189)",
                "posicion"=>12,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Botón Volver al inicio (Fondo)",
                "variable"=>"bg",
                "elemento"=>".btn-principal-style",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63,63,189)",
                "posicion"=>13,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Botón Volver al inicio (Texto)",
                "variable"=>"",
                "elemento"=>".btn-principal-style",
                "propiedad"=>"color",
                "valor"=>"#ffffff",
                "posicion"=>13,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Botón Búsqueda filtros (Fondo)",
                "variable"=>"bg",
                "elemento"=>".btn-buscarfilter-style",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63,63,189)",
                "posicion"=>14,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Botón Búsqueda Filtros (Texto)",
                "variable"=>"",
                "elemento"=>".btn-buscarfilter-style",
                "propiedad"=>"color",
                "valor"=>"#ffffff",
                "posicion"=>14,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Botón Búsqueda Filtros (Fondo al pasr el ratón)",
                "variable"=>"bg",
                "elemento"=>".btn-buscarfilter-style:hover",
                "propiedad"=>"background-color",
                "valor"=>"#000",
                "posicion"=>15,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Botón Búsqueda Filtros (Texto al pasar el ratón)",
                "variable"=>"",
                "elemento"=>".btn-buscarfilter-style:hover",
                "propiedad"=>"color",
                "valor"=>"#fff",
                "posicion"=>15,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Color Slider Precio",
                "variable"=>"bg",
                "elemento"=>".slider-precio-style .noUi-connect",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63,63,189)",
                "posicion"=>16,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Etiqueta activa (fondo)",
                "variable"=>"bg",
                "elemento"=>".tag-style-style",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63,63,189)",
                "posicion"=>17,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Etiqueta activa (texto)",
                "variable"=>"",
                "elemento"=>".tag-style-style",
                "propiedad"=>"color",
                "valor"=>"#fff",
                "posicion"=>17,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Categoría Noticia (fondo)",
                "variable"=>"bg",
                "elemento"=>".category-noticias-style li a",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63,63,189)",
                "posicion"=>18,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Categoría Noticia (texto)",
                "variable"=>"",
                "elemento"=>".category-noticias-style li a",
                "propiedad"=>"color",
                "valor"=>"#fff",
                "posicion"=>18,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Flechas Slider Fotos Producto",
                "variable"=>"",
                "elemento"=>".slider-nav-style .slick-next:before, .slider-nav-style .slick-prev:before",
                "propiedad"=>"color",
                "valor"=>"rgb(63,63,189)",
                "posicion"=>19,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Color Accordiones",
                "variable"=>"",
                "elemento"=>".accordion-button:not(.collapsed)",
                "propiedad"=>"color",
                "valor"=>"rgb(63,63,189)",
                "posicion"=>20,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Breadcrumb Pago (Fondo)",
                "variable"=>"bg",
                "elemento"=>".bitem-style",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63,63,189)",
                "posicion"=>21,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"BreadCrumb Pago (textos)",
                "variable"=>"",
                "elemento"=>".bitem-style",
                "propiedad"=>"color",
                "valor"=>"rgb(63,63,189)",
                "posicion"=>22,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Breadcrumb Pago (Flechas)",
                "variable"=>"bg",
                "elemento"=>".bline-style",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63,63,189)",
                "posicion"=>23,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Botón pagar (fondo)",
                "variable"=>"bg",
                "elemento"=>".btn-pagar-style",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63,63,189)",
                "posicion"=>24,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>1,
                "nombre"=>"Botón Pagar (texto)",
                "variable"=>"",
                "elemento"=>".btn-pagar-style",
                "propiedad"=>"color",
                "valor"=>"rgb(63,63,189)",
                "posicion"=>24,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Barra de Progreso Pago",
                "variable"=>"bg",
                "elemento"=>".progress-style",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63,63,189)",
                "posicion"=>25,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
            [
                "estilo_tipo_id"=>2,
                "nombre"=>"Barra de Progreso activa",
                "variable"=>"bg",
                "elemento"=>".progress-step-active",
                "propiedad"=>"background-color",
                "valor"=>"rgb(63,63,189)",
                "posicion"=>26,
                "oculto"=>0,
                "usuario_registro"=>"admin",
                "fecha_registro"=>now()
            ],
        ];

        Estilo::insert($estilos);
    }
}
