version: '3.8'

services:
  valtecgda_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: valtecgda_app
    labels:
      - "traefik.enable=true"
      # Regla para HTTP
      - "traefik.http.routers.valtecgda_http.rule=Host(`www.valtecgda.com`)"
      - "traefik.http.routers.valtecgda_http.entrypoints=web"
      # Opcional: redirigir todo el tráfico HTTP a HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.valtecgda_http.middlewares=redirect-to-https"

      - "traefik.http.routers.valtecgda_app.rule=Host(`www.valtecgda.com`)"
      - "traefik.http.routers.valtecgda_app.entrypoints=web"
      - "traefik.http.routers.valtecgda_app.entrypoints=websecure"
      - "traefik.http.routers.valtecgda_app.tls.certresolver=myresolver"    
    volumes:
      - .:/app
    networks:
      - traefik
    env_file:
      - .env

  valtec_db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secure_root_password_123
      MYSQL_DATABASE: valtec_db
      MYSQL_USER: user
      MYSQL_PASSWORD: secure_db_password_123
    volumes:
      - /docker/valtecgda/mariadb_data:/var/lib/mysql
      - ./valtec.sql:/docker-entrypoint-initdb.d/valtec.sql
    networks:
      - traefik

volumes:
  storage:  

networks:
  traefik:
    driver: bridge
    name: docker_traefik
